# fly.toml app configuration file generated for hommy on 2025-08-18T12:14:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hommy'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "wa_sessions"
  destination = "/app/sessions-inquilinos"

[env]
  SESSION_PATH = "/app/sessions-inquilinos"
