# fly.toml app configuration file generated for wa-sender-icy-pine-5127 on 2025-08-21T10:29:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wa-sender-icy-pine-5127'
primary_region = 'mad'

[build]
  dockerfile = './Dockerfile'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
