[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "whatsapp-bot"
protocol = "HTTP"
port = 3000

[experimental]
configVersion = 2